In [2]:
import numpy as np
np.__version__

'1.16.3'

# 数组初始化

In [42]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [49]:
import math
np.full((3, 5), math.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [51]:
np.arange(0, 20, 2).reshape(5, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [53]:
np.linspace(0, 2, 20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [55]:
#均匀分布
np.random.random((3, 3))

array([[0.14194969, 0.43305551, 0.75094392],
       [0.57186138, 0.97016388, 0.83113967],
       [0.18406927, 0.42366427, 0.21268046]])

In [57]:
np.random.normal(0, 1, (3, 3))
#正态分布

array([[ 0.07243531, -1.96461681,  0.27854179],
       [ 0.88973286, -0.4268119 ,  1.06724698],
       [-1.14869704, -1.37463791, -1.79093478]])

In [58]:
np.random.normal?

In [59]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.random.randint(0, 10, (3, 3))

array([[7, 0, 5],
       [9, 8, 6],
       [3, 6, 4]])

In [63]:
np.empty(100).reshape(10, 10)

array([[6.01100539e+175, 9.20074431e+170, 4.31814707e-096,
        7.26807707e+223, 4.50622032e-144, 1.66078827e+243,
        1.29060661e+248, 1.16071791e-028, 1.29060661e+248,
        8.42244190e+252],
       [3.77780808e+180, 1.15998412e-028, 1.16568549e+253,
        7.49511203e+247, 1.12284826e+219, 2.89848970e+131,
        1.04796651e-142, 6.01409647e+175, 5.22151366e+180,
        6.01100500e+175],
       [5.49419094e-143, 1.67856307e+243, 8.76794568e+252,
        1.08597099e-095, 8.17330861e-043, 1.16467185e-028,
        4.30442792e-096, 8.37170577e-144, 5.23988733e-143,
        9.31115231e+242],
       [1.47281197e+179, 4.51919969e-144, 9.68109906e+183,
        6.32275946e+233, 3.27555068e+267, 1.39274686e-142,
        9.69385795e-067, 1.16071791e-028, 1.11789342e+253,
        4.50618855e-144],
       [1.17037300e+208, 5.87331772e+294, 8.42244189e+252,
        6.11136131e+223, 2.60223351e+251, 7.26813884e+223,
        5.49419094e-143, 1.67856307e+243, 8.76794568e+252,
        1.0

In [67]:
np.typeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.int64,
 'q': numpy.int64,
 9: numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 10: numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,


In [72]:
np.random.seed(0)
x1 = np.random.randint(190, size=6)
print(f'{x1.ndim} {x1.shape} {x1.size} {x1.dtype} {x1.nbytes}')

1 (6,) 6 int64 48 8


In [90]:
a = np.random.randint(0, 100, (5, 5))
print(a)


[[67 82 46 99 20]
 [81 50 27 14 41]
 [58 65 36 10 86]
 [43 11  2 51 80]
 [32 54  0 38 19]]


array([[67, 82],
       [81, 50]])

In [93]:
a[:2, 1:2]
#是原来的视图， 并不是另一份数组

array([[82],
       [50]])

In [94]:
a[:2, 1:2].copy()

array([[82],
       [50]])

# 数组合并


In [97]:

x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
z = np.array([3, 4, 5])
np.concatenate([x, y, z])

array([1, 2, 3, 2, 3, 4, 3, 4, 5])

In [99]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
#沿着第一个轴添加
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [101]:
#沿着第二轴添加，轴数不能超过维度
np.concatenate([grid, grid], axis=1)

AxisError: axis 2 is out of bounds for array of dimension 2

In [102]:
np.vstack([grid, grid])
#垂直轴添加
#等价于 np.row_stack

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [103]:
np.hstack([grid, grid])
#水平轴添加
#等价于np.column_stack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [106]:
#np.*stack?


In [107]:
#np.dstack 按第三维度添加

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# 分裂

In [114]:
x = [i for i in range(10)]
#第一个参数是数组， 第二个参数是元组或者列表封装的分裂点
np.split(x, (3, 5))

[array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8, 9])]

In [116]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
np.split(grid, [2, 3], axis=1)
#类似连接

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

In [119]:
np.vsplit(grid, [2, 3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [120]:
np.hsplit(grid, [2, 3])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

# 通用函数
## 一元通用函数


In [126]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [127]:
a + 5

array([6, 7, 8, 9])

In [128]:
1 / a

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [129]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [131]:
a * 2

array([2, 4, 6, 8])

In [132]:
a ** 2

array([ 1,  4,  9, 16])

In [133]:
a % 2

array([1, 0, 1, 0])

In [134]:
b = np.array([-1, 2, -3, 4])
np.abs(b)

array([1, 2, 3, 4])

In [3]:
a = np.array([[1, 2],
             [3, 4]])
b = np.array([[1], 
        [2]])
a * b
#数组的默认乘法是对位相乘

array([[1, 2],
       [6, 8]])

In [137]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [138]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [139]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [141]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [142]:
# 同样支持 反三角函数
c = np.array([-1, 0, 1])
np.arcsin(c)

array([-1.57079633,  0.        ,  1.57079633])

In [143]:
np.arccos(c)

array([3.14159265, 1.57079633, 0.        ])

In [144]:
np.arctan(c)

array([-0.78539816,  0.        ,  0.78539816])

## scipy中拓展的高级函数

In [145]:
from scipy import special as sp
x = np.array([1, 5, 10])
sp.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [146]:
sp.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [147]:
sp.beta(x, 2)

array([0.5       , 0.03333333, 0.00909091])

In [149]:
#误差函数（高斯积分）
#它的实现和逆实现
x = np.array([0, 0.3, 0.7, 1.0])
sp.erf(x)

array([0.        , 0.32862676, 0.67780119, 0.84270079])

In [150]:
sp.erfc(x)

array([1.        , 0.67137324, 0.32219881, 0.15729921])

In [151]:
sp.erfinv(x)

array([0.        , 0.27246271, 0.73286908,        inf])

##  高级通用函数特性

In [155]:
#用out制定输出位置， 可以避免创建一个临时数组
x = np.arange(5)
y = x * 10
y

array([ 0, 10, 20, 30, 40])

In [157]:
z = np.zeros(10)
np.power(2, x, out=z[::2])
z
#如果写成下面的形式，会创建临时变量
z[::2] = x ** 2
z

array([ 0.,  0.,  1.,  0.,  4.,  0.,  9.,  0., 16.,  0.])

In [162]:
x = np.arange(1, 6)
np.add.reduce(x)


15

In [163]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

np.add np.multiply这种函数，是可调用类，而不是普通的方法

In [164]:
#外积
#任何通用函数都可以使用outer方法获得不同输入数组所有元素对的运算结果
x = np.arange(1, 10)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [165]:
np.add.outer(x, x)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [166]:
import matplotlib as mpl
from matplotlib import pyplot as plt

'3.0.3'

In [1]:
a = "asdasda"
b = "asdasd"
a + b

'asdasdaasdasd'

In [2]:
a = 1 

a *= a

a

1

In [3]:
a += 1

In [4]:
a 

2